"""Generate paper/generated/results.tex from all reference_summary.json files.

Every result value the paper prints flows through a macro emitted here — nothing is
hand-typed into the .tex (no-fabrication rule). A value that does not exist yet
(experiment not run) is emitted as ``\\pending{<id>}`` which renders "— [pending: id]".

Run via ``make paper`` (or directly). Reads:
  - paper/data/phase0/reference_summary.json  (real live pilot numbers)
  - paper/data/<exp>/reference_summary.json    (experiment results, when present)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "paper" / "data"
OUT = ROOT / "paper" / "generated" / "results.tex"

EXPERIMENTS = [
    "h1-full",
    "h1-ladder",
    "h2-detection",
    "h3-frontier",
    "h4-recovery",
    "ablations",
    "tier2-validation",
]


def _load(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        data: dict[str, Any] = json.loads(path.read_text())
        return data
    except Exception:
        return None


def _pct(x: Any) -> str | None:
    return f"{round(float(x) * 100)}\\%" if isinstance(x, (int, float)) else None


def _num(x: Any, dec: int = 3) -> str | None:
    return f"{float(x):.{dec}f}" if isinstance(x, (int, float)) else None


def macro(name: str, value: str | None, pending_id: str) -> str:
    body = value if value is not None else f"\\pending{{{pending_id}}}"
    return f"\\newcommand{{\\{name}}}{{{body}}}"


def build() -> list[str]:
    lines = [
        "% AUTO-GENERATED by paper/scripts/make_macros.py — do not edit by hand.",
        "\\providecommand{\\pending}[1]{\\textbf{--}~\\texttt{[pending:~#1]}}",
        "",
    ]

    p0 = _load(DATA / "phase0" / "reference_summary.json") or {"runs": {}}
    runs = p0.get("runs", {})
    a, b, c = runs.get("phase0a", {}), runs.get("phase0b", {}), runs.get("phase0c", {})
    # 0a elasticity / clean-regret are derived post-hoc from the results-branch JSONL
    # (scripts/derive_phase0a_metrics.py); prefer the derived file when present.
    a_deriv = _load(DATA / "phase0" / "phase0a_derived.summary.json") or {}

    lines += [
        "% --- Phase 0 pilot (real live numbers) ---",
        macro("PhaseZeroSpend", _num(p0.get("spend_total_usd"), 2), "phase0-spend"),
        macro("PZaScored", str(a.get("n_scored", "")) or None, "phase0a"),
        macro("PZaAdr", _pct(a.get("adr")), "phase0a"),
        macro("PZaOracleAdr", _pct(a.get("oracle_adr")), "phase0a"),
        macro(
            "PZaElasticity",
            _num(a_deriv.get("elasticity_median"), 3)
            if a_deriv.get("elasticity_median") is not None
            else (
                _num(a.get("elasticity_median"), 3)
                if a.get("elasticity_median") is not None
                else None
            ),
            "phase0a-elasticity",
        ),
        macro(
            "PZaRegret",
            _num(a_deriv.get("clean_regret_median"), 0)
            if a_deriv.get("clean_regret_median") is not None
            else None,
            "phase0a-regret",
        ),
        macro("PZbScored", str(b.get("n_scored", "")) or None, "phase0b"),
        macro("PZbElasticity", _num(b.get("elasticity_median"), 3), "phase0b"),
        macro("PZcScored", str(c.get("n_scored", "")) or None, "phase0c"),
        macro("PZcEpisodes", str(c.get("n_episodes", "")) or None, "phase0c"),
        macro("PZcAdr", _pct(c.get("adr")), "phase0c"),
        macro("PZcOracleAdr", _pct(c.get("oracle_adr")), "phase0c"),
        macro("PZcElasticity", _num(c.get("elasticity_median"), 3), "phase0c"),
        macro("PZcMarkerAuc", _num(c.get("marker_auc"), 3), "phase0c"),
        macro("PZcJudgeAuc", _num(c.get("judge_auc"), 3), "phase0c"),
        macro("PZcFlags", _pct(c.get("flagged_fraction")), "phase0c"),
        "",
        "% --- Experiments H1-H4 (pending until fired) ---",
    ]

    # --- Per-experiment macros from the ingested reference summaries. Each Res<Cap> is a
    # one-word verdict; the supporting numbers the Results prose cites get their own macros.
    def rung(s: dict[str, Any], model: str, key: str) -> Any:
        return (s.get("rungs", {}) or {}).get(model, {}).get(key)

    hone = _load(DATA / "h1-full" / "reference_summary.json") or {}
    lad = _load(DATA / "h1-ladder" / "reference_summary.json") or {}
    htwo = _load(DATA / "h2-detection" / "reference_summary.json") or {}
    hthree = _load(DATA / "h3-frontier" / "reference_summary.json") or {}
    hfour = _load(DATA / "h4-recovery" / "reference_summary.json") or {}
    abl = _load(DATA / "ablations" / "reference_summary.json")
    tier = _load(DATA / "tier2-validation" / "reference_summary.json")
    haiku_adr = _pct(rung(lad, "claude-haiku-4-5", "metadata_borne_adr"))
    fable_adr = _pct(rung(lad, "claude-fable-5", "metadata_borne_adr"))
    abl_head = _num(abl["headline"]) if isinstance(abl, dict) else None
    tier_head = _num(tier["headline"]) if isinstance(tier, dict) else None

    lines += [
        # H1 full — silence + loss-conversion under the competent decider.
        macro("ResHoneFull", "SUPPORTED" if hone else None, "h1-full"),
        macro("HoneFullMetaAdr", _pct(hone.get("metadata_borne_adr")), "h1-full"),
        # H1 capability ladder — flat across haiku->sonnet->opus->fable (the headline).
        macro("ResHoneLadder", "SUPPORTED" if lad else None, "h1-ladder"),
        macro("HoneLadderAdrLo", _pct(lad.get("adr_min")), "h1-ladder"),
        macro("HoneLadderAdrHi", _pct(lad.get("adr_max")), "h1-ladder"),
        macro("HoneLadderFlag", _pct(lad.get("flag_fraction_max")), "h1-ladder"),
        macro("HoneLadderAuc", _num(lad.get("marker_auc_max"), 2), "h1-ladder"),
        macro("HoneLadderAdrHaiku", haiku_adr, "h1l"),
        macro("HoneLadderAdrFable", fable_adr, "h1l"),
        # H2 detection asymmetry — reframed as a channel boundary.
        macro("ResHtwo", "REFRAMED" if htwo else None, "h2-detection"),
        macro("HtwoCriticMeta", _pct(htwo.get("critic_detection_metadata")), "h2-detection"),
        macro("HtwoGateMeta", _pct(htwo.get("gate_detection_metadata")), "h2-detection"),
        # H3 gating dominance — not supported as written; gate beats the realistic critic.
        macro("ResHthree", "NOT SUPPORTED" if hthree else None, "h3-frontier"),
        macro("HthreeGateDet", _pct(hthree.get("gate_detection")), "h3-frontier"),
        macro("HthreeCriticDet", _pct(hthree.get("critic_detection")), "h3-frontier"),
        macro("HthreeGateResid", _num(hthree.get("gate_residual_loss"), 0), "h3-frontier"),
        macro("HthreeCriticResid", _num(hthree.get("critic_residual_loss"), 0), "h3-frontier"),
        macro("HthreeFalseBlock", _pct(hthree.get("gate_false_block")), "h3-frontier"),
        # H4 downstream sufficiency — not supported at portfolio; freshness recovered.
        macro("ResHfour", "NOT SUPPORTED" if hfour else None, "h4-recovery"),
        macro("HfourRecovery", _num(hfour.get("portfolio_recovery"), 2), "h4-recovery"),
        macro("HfourStaleLossA", _num(hfour.get("stale_loss_a"), 0), "h4-recovery"),
        macro("HfourStaleLossD", _num(hfour.get("stale_loss_d"), 1), "h4-recovery"),
        # Not run.
        macro("ResAblations", abl_head, "ablations"),
        macro("ResTier", tier_head, "tier2-validation"),
    ]
    return lines


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(build()) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
