"""Generate paper/generated/results.tex from all reference_summary.json files.

Every result value the paper prints flows through a macro emitted here — nothing is
hand-typed into the .tex (no-fabrication rule). A value that does not exist yet
(experiment not run) is emitted as ``\\pending{<id>}`` which renders "— [pending: id]".

Run via ``make paper`` (or directly). Reads:
  - paper/data/phase0/reference_summary.json  (real live pilot numbers)
  - paper/data/<exp>/reference_summary.json    (experiment results, when present)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "paper" / "data"
OUT = ROOT / "paper" / "generated" / "results.tex"

EXPERIMENTS = [
    "h1-full",
    "h1-ladder",
    "h2-detection",
    "h3-frontier",
    "h4-recovery",
    "ablations",
    "tier2-validation",
]


def _load(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        data: dict[str, Any] = json.loads(path.read_text())
        return data
    except Exception:
        return None


def _pct(x: Any) -> str | None:
    return f"{round(float(x) * 100)}\\%" if isinstance(x, (int, float)) else None


def _num(x: Any, dec: int = 3) -> str | None:
    return f"{float(x):.{dec}f}" if isinstance(x, (int, float)) else None


def macro(name: str, value: str | None, pending_id: str) -> str:
    body = value if value is not None else f"\\pending{{{pending_id}}}"
    return f"\\newcommand{{\\{name}}}{{{body}}}"


def build() -> list[str]:
    lines = [
        "% AUTO-GENERATED by paper/scripts/make_macros.py — do not edit by hand.",
        "\\providecommand{\\pending}[1]{\\textbf{--}~\\texttt{[pending:~#1]}}",
        "",
    ]

    p0 = _load(DATA / "phase0" / "reference_summary.json") or {"runs": {}}
    runs = p0.get("runs", {})
    a, b, c = runs.get("phase0a", {}), runs.get("phase0b", {}), runs.get("phase0c", {})
    # 0a elasticity / clean-regret are derived post-hoc from the results-branch JSONL
    # (scripts/derive_phase0a_metrics.py); prefer the derived file when present.
    a_deriv = _load(DATA / "phase0" / "phase0a_derived.summary.json") or {}

    lines += [
        "% --- Phase 0 pilot (real live numbers) ---",
        macro("PhaseZeroSpend", _num(p0.get("spend_total_usd"), 2), "phase0-spend"),
        macro("PZaScored", str(a.get("n_scored", "")) or None, "phase0a"),
        macro("PZaAdr", _pct(a.get("adr")), "phase0a"),
        macro("PZaOracleAdr", _pct(a.get("oracle_adr")), "phase0a"),
        macro(
            "PZaElasticity",
            _num(a_deriv.get("elasticity_median"), 3)
            if a_deriv.get("elasticity_median") is not None
            else (
                _num(a.get("elasticity_median"), 3)
                if a.get("elasticity_median") is not None
                else None
            ),
            "phase0a-elasticity",
        ),
        macro(
            "PZaRegret",
            _num(a_deriv.get("clean_regret_median"), 0)
            if a_deriv.get("clean_regret_median") is not None
            else None,
            "phase0a-regret",
        ),
        macro("PZbScored", str(b.get("n_scored", "")) or None, "phase0b"),
        macro("PZbElasticity", _num(b.get("elasticity_median"), 3), "phase0b"),
        macro("PZcScored", str(c.get("n_scored", "")) or None, "phase0c"),
        macro("PZcEpisodes", str(c.get("n_episodes", "")) or None, "phase0c"),
        macro("PZcAdr", _pct(c.get("adr")), "phase0c"),
        macro("PZcOracleAdr", _pct(c.get("oracle_adr")), "phase0c"),
        macro("PZcElasticity", _num(c.get("elasticity_median"), 3), "phase0c"),
        macro("PZcMarkerAuc", _num(c.get("marker_auc"), 3), "phase0c"),
        macro("PZcJudgeAuc", _num(c.get("judge_auc"), 3), "phase0c"),
        macro("PZcFlags", _pct(c.get("flagged_fraction")), "phase0c"),
        "",
        "% --- Experiments H1-H4 (pending until fired) ---",
    ]

    cap = {
        "h1-full": "HoneFull",
        "h1-ladder": "HoneLadder",
        "h2-detection": "Htwo",
        "h3-frontier": "Hthree",
        "h4-recovery": "Hfour",
        "ablations": "Ablations",
        "tier2-validation": "Tier",
    }
    for exp in EXPERIMENTS:
        summ = _load(DATA / exp / "reference_summary.json")
        # Headline macro per experiment: a scalar if the run exists, else pending.
        val = _num(summ.get("headline")) if isinstance(summ, dict) else None
        lines.append(macro(f"Res{cap[exp]}", val, exp))
    return lines


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(build()) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
