"""Emit ``paper/generated/analysis.tex`` --- every number the analytical appendix prints.

Same no-fabrication discipline as ``paper/scripts/make_macros.py``: the appendix never
hand-types a value; each flows through a ``\\newcommand`` generated here from the committed
``analysis/out/*.json``. Run as part of ``make analysis`` (after the modules have written
their JSON). Deterministic; reads only local files.
"""

from __future__ import annotations

import json
from typing import Any

from analysis.common import ROOT

OUT_JSON = ROOT / "analysis" / "out"
OUT_TEX = ROOT / "paper" / "generated" / "analysis.tex"


def _load(name: str) -> dict[str, Any]:
    data: dict[str, Any] = json.loads((OUT_JSON / name).read_text())
    return data


def _num(x: float, places: int = 3) -> str:
    return f"{x:.{places}f}"


def _texttt(name: str) -> str:
    """A class name, safe for LaTeX text (underscores escaped), in \\texttt."""
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def build_macros() -> dict[str, str]:
    conv = _load("conversion_law.json")
    cov = _load("coverage_accounting.json")
    rob = _load("robustness.json")
    strs = _load("stress.json")
    fals = _load("falsification.json")
    sec = _load("second_domain.json")
    stat = _load("stats_tables.json")

    m: dict[str, str] = {}

    # #4 ladder flatness (statistical)
    h1 = stat["h1_ladder"]
    ep = h1["endpoint_difference"]
    m["LadderEndpointDiff"] = _num(ep["top_minus_bottom"], 4)
    m["LadderEndpointCILo"] = _num(ep["ci95"][0], 4)
    m["LadderEndpointCIHi"] = _num(ep["ci95"][1], 4)
    m["LadderTrendPerTier"] = _num(h1["ols_trend_per_tier"], 4)

    # Stage 2A: H2 per-class Wilson 95% CIs (integer percent, matching the point-estimate macros)
    h2 = stat["h2_detection"]
    m["HtwoDetN"] = str(h2["n_per_class"])
    for r in h2["rows"]:
        key = r["key"]
        cl, ch = r["critic"]["ci95_pct"]
        gl, gh = r["gate"]["ci95_pct"]
        m[f"HtwoCI{key}CLo"] = str(cl)
        m[f"HtwoCI{key}CHi"] = str(ch)
        m[f"HtwoCI{key}GLo"] = str(gl)
        m[f"HtwoCI{key}GHi"] = str(gh)

    # Stage 2A: H3/H4 residual-loss bootstrap 95% CIs (point estimates already in results.tex)
    q = stat["h3h4_residual"]
    m["BootReplicates"] = str(q["bootstrap_replicates"])
    m["BootSeed"] = str(q["bootstrap_seed"])
    for name, key in (
        ("h3_gate_residual", "HthreeGateResid"),
        ("h3_critic_residual", "HthreeCriticResid"),
        ("h4_stale_loss_a", "HfourStaleLossA"),
        ("h4_stale_loss_d", "HfourStaleLossD"),
    ):
        lo, hi = q["quantities"][name]["ci95"]
        m[f"{key}Lo"] = _num(lo, 1)
        m[f"{key}Hi"] = _num(hi, 1)

    # #1 conversion law
    m["ConvNCells"] = str(conv["n_cells"])
    m["ConvMAE"] = _num(conv["mean_abs_error"], 3)
    m["ConvR"] = _num(conv["pearson_pred_vs_measured"], 3)
    m["ConvCICoverage"] = conv["ci_coverage"]

    # #2 coverage accounting
    m["CovRecovery"] = _num(cov["recovery_from_identity"], 4)
    m["CovResidual"] = _num(cov["residual"], 6)
    m["CovDominant"] = _texttt(cov["dominant_class"])
    m["CovDominantSharePct"] = str(int(round(100 * cov["dominant_den_share"])))

    # #5 leave-one-out (full + the swing when the dominant uncovered class is removed)
    loo = rob["loo"]
    m["LooFull"] = _num(loo["full_recovery"], 4)
    top = loo["leave_one_out"][0]
    m["LooTopClass"] = _texttt(top["excluded"])
    m["LooTopRecovery"] = _num(top["recovery"], 4)

    # #4 threshold sensitivity (registered point + endpoints of the sweep)
    curve = {c["tau_m"]: c["mean_oracle_adr"] for c in rob["threshold_sensitivity"]["curve"]}
    reg = rob["threshold_sensitivity"]["registered_tau_m"]
    m["ThreshReg"] = _num(reg, 3)
    m["ThreshRegAdr"] = _num(curve[reg], 4)
    m["ThreshLoAdr"] = _num(curve[min(curve)], 4)
    m["ThreshHiAdr"] = _num(curve[max(curve)], 4)

    # #7 stress
    pooled = strs["pooled_detection_by_mode"]
    m["StressIntact"] = _num(pooled["intact"], 4)
    m["StressAllDegraded"] = _num(pooled["all_degraded"], 4)
    m["StressFragile"] = _texttt(strs["most_fragile_class"])

    # #8 falsification
    rec = fals["recovered_fraction"]
    m["FalsGate"] = _num(rec["gate_real"], 4)
    m["FalsRandom"] = _num(rec["random_match"], 4)
    m["FalsShuffled"] = _num(rec["shuffled_flags"], 4)
    m["FalsAnti"] = _num(rec["anti_correlated"], 4)
    m["FalsGap"] = _num(fals["gate_minus_random"], 4)

    # #10 second domain
    m["SecondADR"] = _num(sec["portfolio_adr"], 4)
    m["SecondRecovery"] = _num(sec["portfolio_gate_recovery"], 4)
    by = {r["class"]: r for r in sec["rows"]}
    m["SecondExpiredADR"] = _num(by["expired_campaign"]["adr"], 4)
    m["SecondConsentADR"] = _num(by["missing_consent"]["adr"], 4)

    return m


def render(macros: dict[str, str]) -> str:
    lines = [
        "% AUTO-GENERATED by analysis/make_analysis_macros.py (make analysis). Do not edit.",
        "% Every value is a deterministic recomputation from committed data (analysis/out).",
    ]
    for k, v in macros.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    return "\n".join(lines) + "\n"


def main() -> int:
    macros = build_macros()
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(render(macros), encoding="utf-8")
    print(f"wrote {OUT_TEX.relative_to(ROOT)} ({len(macros)} macros)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
